version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "3000:3000"
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - .:/app
    depends_on:
      - db
    command: >
      bash -c "
        rm -f tmp/pids/server.pid &&
        bundle exec rails db:create &&
        bundle exec rails db:migrate &&
        bundle exec rails server -b 0.0.0.0
      "

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
